config/routes.rb
FirstApp::Application.routes.draw do
  resources :pairings do
    collection do
      post :batch, as: :batch
    end
  end

  resources :memberships

  resources :teams

  resources :people

  get "pages/home"

  get "pages/roster"

  root to: 'pairings#index'
  

end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id         :integer          not null, primary key
#  person_id  :integer
#  team_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Membership < ActiveRecord::Base
  attr_accessible :person_id, :team_id

  belongs_to :person
  belongs_to :team

  validates :person_id, presence: true
  validates :team_id, presence: true
  validates :person_id, :uniqueness => {:scope => :team_id}

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
    @teams = Team.all

    @team_rosters = {}
    @teams.each do |team|
      @team_rosters[team.id] = Membership.where(team_id: team.id)
      @team_rosters[team.id].sort! {|a,b| a.person.name <=> b.person.name}
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.json
  def new
    @membership = Membership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(params[:membership])

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render json: @membership, status: :created, location: @membership }
      else
        format.html { render action: "new" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.json
  def update
    @membership = Membership.find(params[:id])

    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id, "Name:" %>
    <%= f.collection_select :person_id, Person.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :team_id, "Team:" %>
    <%= f.collection_select :team_id, Team.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit "Add to team"%>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Team Rosters</h1>

<%= button_to 'Make a Team', new_team_path, method: :get, class: "btn btn-primary" %>
<% @teams.each do |team| %>

<h2>
  <%= team.name %>
</h2>
<table class="table table-hover table-condensed">
  <tr>
    <th><h3>Name</h3></th>
    <th><h3>Email</h3></th>
    <th></th>
    <th></th>
  </tr>

<% @team_rosters[team.id].each do |member| %> 
  <tr>
    <td><%= member.person.name %></td>
    <td><%= member.person.email %></td>
    <td><%= link_to 'X', member, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small" %></td>
  </tr>
<% end %>
</table>

<%= form_for Membership.new do |f| %>
<p>
  <%= f.collection_select :person_id, Person.order("name ASC"), :id, :name, {prompt: 'Select name', class: "dropdown"} %>
  <%= f.hidden_field :team_id, value: team.id %>
  <%= f.submit "Add to team", class: "btn btn-small btn-primary"  %>
</p>
<% end %>

<br />

<% end %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Person:</b>
  <%= @membership.person_id %>
</p>

<p>
  <b>Team:</b>
  <%= @membership.team_id %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>