config/routes.rb
FirstApp::Application.routes.draw do
  resources :pairings do
    collection do
      post :batch, as: :batch
    end
  end

  resources :memberships

  resources :teams

  resources :people

  get "pages/home"

  get "pages/roster"

  root to: 'pairings#index'
  

end

app/models/pairing.rb
# == Schema Information
#
# Table name: pairings
#
#  id           :integer          not null, primary key
#  person_id    :integer
#  pair_id      :integer
#  pairing_date :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Pairing < ActiveRecord::Base
  attr_accessible :pair_id, :pairing_date, :person_id

  belongs_to :person
  belongs_to :pair, class_name: "Person"

  validates :person_id, presence: true
  validates :pair_id, presence: true
  validates :pairing_date, presence: true

  validate :cannot_pair_self

  def cannot_pair_self
  	if self.person_id == self.pair_id
  		errors[:base] << 'You cannot pair with yourself on a 1+1.'
  	end
  end
end

app/controllers/pairings_controller.rb
class PairingsController < ApplicationController
  # GET /pairings
  # GET /pairings.json
  def index
    @pairings = Pairing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pairings }
    end
  end

  # GET /pairings/1
  # GET /pairings/1.json
  def show
    @pairing = Pairing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pairing }
    end
  end

  # GET /pairings/new
  # GET /pairings/new.json
  def new
    @pairing = Pairing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pairing }
    end
  end

  # GET /pairings/1/edit
  def edit
    @pairing = Pairing.find(params[:id])
  end

  # POST /pairings
  # POST /pairings.json
  def create
    @pairing = Pairing.new(params[:pairing])

    respond_to do |format|
      if @pairing.save
        format.html { redirect_to @pairing, notice: 'Pairing was successfully created.' }
        format.json { render json: @pairing, status: :created, location: @pairing }
      else
        format.html { render action: "new" }
        format.json { render json: @pairing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pairings/1
  # PUT /pairings/1.json
  def update
    @pairing = Pairing.find(params[:id])

    respond_to do |format|
      if @pairing.update_attributes(params[:pairing])
        format.html { redirect_to @pairing, notice: 'Pairing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pairing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pairings/1
  # DELETE /pairings/1.json
  def destroy
    @pairing = Pairing.find(params[:id])
    @pairing.destroy

    respond_to do |format|
      format.html { redirect_to pairings_url }
      format.json { head :no_content }
    end
  end

  # POST /pairings/batch
  def batch
    @valid_pairings = []
    @timestamp = DateTime.now
    @unavailable_people = Set.new()

    generate_valid_pairings(@valid_pairings)
    sort_valid_pairings_by_staleness(@valid_pairings)

    @valid_pairings.each do |pairing|
      if people_are_available?(pairing, @unavailable_people)
        pairing.pairing_date = @timestamp

        if pairing.save
          @unavailable_people.add(pairing.person)
          @unavailable_people.add(pairing.pair)
          
          # PersonMailer.weekly_pairing(pairing).deliver
        else
          redirect_to pairings_url, notice: "Failed to create pairing <#{pairing.person}, #{pairing.pair}>"
        end
      end
    end
    # puts 'emailing all pairings?'
    # PersonMailer.all_pairings
    redirect_to pairings_url, notice: "Successfully generated pairings for #{@timestamp.to_formatted_s(:long)}"
  end

end

app/helpers/pairings_helper.rb
module PairingsHelper
end

app/views/pairings/_form.html.erb
<%= form_for(@pairing) do |f| %>
  <% if @pairing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pairing.errors.count, "error") %> prohibited this pairing from being saved:</h2>

      <ul>
      <% @pairing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.number_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :pair_id %><br />
    <%= f.number_field :pair_id %>
  </div>
  <div class="field">
    <%= f.label :pairing_date %><br />
    <%= f.datetime_select :pairing_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pairings/edit.html.erb
<h1>Editing pairing</h1>

<%= render 'form' %>

<%= link_to 'Show', @pairing %> |
<%= link_to 'Back', pairings_path %>

app/views/pairings/index.html.erb
<h1>1+1 Pairings</h1>

<table class="table table-hover table-condensed">
  <tr>
    <th><h2>Person 1 </h2></th>
    <th><h2>Person 2</h2></th>
    <th><h2>Date</h2></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pairings.each do |pairing| %>
  <tr>
    <td><%= pairing.person.name %></td>
    <td><%= pairing.pair.name %></td>
    <td><%= pairing.pairing_date.to_formatted_s(:long) %></td>
    <!-- <td><%= link_to 'Edit', edit_pairing_path(pairing) %></td> -->
    <td><%= link_to 'X', pairing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small" %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'Generate pairings', batch_pairings_path, method: :post, class: "btn btn-primary" %>

app/views/pairings/new.html.erb
<h1>New pairing</h1>

<%= render 'form' %>

<%= link_to 'Back', pairings_path %>

app/views/pairings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Person:</b>
  <%= @pairing.person_id %>
</p>

<p>
  <b>Pair:</b>
  <%= @pairing.pair_id %>
</p>

<p>
  <b>Pairing date:</b>
  <%= @pairing.pairing_date %>
</p>


<%= link_to 'Edit', edit_pairing_path(@pairing) %> |
<%= link_to 'Back', pairings_path %>